### GET /
GET http://localhost:8000

### Register a user POST /auth/register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "Alex_Josdf2342",
    "password": "qwerty"
}

### Login a user POST /auth/login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "Alex_Josdf2342",
    "password": "qwerty"
}